name: Release Drafter

on:
  push:
    branches:
      - main
      
jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update release draft
      uses: release-drafter/release-drafter@v6
      with:
        publish: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
